### ISSUE TITLE
The database user for this connection is not allowed to read drives.

### ISSUE THREAD

**Issue by rasoolghafari** [nvdweem/intellij-sqlserver-backup-restore#10]
I installed this plugin, but when i want to make backup, i get this error:

The database user for this connection is not allowed to read drives.

**Comment by nvdweem** [comment]
This seems to be caused by the plugin using `xp_fixeddrives` and `xp_dirtree` for the filetree population. In 0.8.0 (pending moderation) it should use a similar method as SSMS does which doesn't require the sysadmin role.
