### ISSUE TITLE
Unable to restore databse

### ISSUE THREAD

**Issue by mikart143** [nvdweem/intellij-sqlserver-backup-restore#11]
Hello!
First! Thanks for plugin ! 
I have a small problem with restoring databse from file.
When I use restore option I am getting an error.
```
The operating system returned the error '267(The directory name is invalid.)' while attempting 'RestoreContainer::ValidateTargetForCreation' on '/var/opt/mssql/data/XXX_log.ldf\YYY.mdf'.

```
I am using 2019 Sql Server on docker. 
I am using Manjaro 20 with btrfs file system.
I am able to restore this databse on windows and also with azure data studio on linux.

**Comment by nvdweem** [comment]
The plugin was expecting some backslashes in certain places for files. In 0.8.0 it should support slashes too which should make it compatible with SQLServer on docker.
