### ISSUE TITLE
Add an ability to specify target filenames when restoring

### ISSUE THREAD

**Issue by bearpawmaxim** [nvdweem/intellij-sqlserver-backup-restore#13]
It would be nice if the user could specify the recovery file names (for data and log) before restoring the database as it is possible in SSMS under Files tab of Restore dialog.

**Comment by nvdweem** [comment]
The 0.8.0 version will have an option in the settings that adds a dialog to set the filenames when restoring. It's a bit minimalistic because I don't actually use this myself.

**Comment by bearpawmaxim** [comment]
Thanks! Will try!
