### ISSUE TITLE
Storing the bak file from the MAC OS file location using Rider of SQL server in Docker

### ISSUE THREAD

**Issue by anandjaisy** [nvdweem/intellij-sqlserver-backup-restore#16]
Using the plugin in the latest version of Rider with SQL on docker the location of the bak file cannot be browsed.

![image](https://user-images.githubusercontent.com/1625641/108022091-00fc8b00-7074-11eb-9979-5404016b1f53.png)

The file is located on the desktop, how can we browse the file

**Comment by nvdweem** [comment]
I'm expecting that you don't mean the desktop inside the docker container?

SQLServer only allows restoring backups that the database can reach. If the location of the file isn't volume mapped in the docker container then you won't be able to select it. For this usecase I would suggest adding a volume mapping to the host and put your backups there.

As far as I know there is no way to select a local file and stream it to the server.
