### ISSUE TITLE
Check if compressed backups are supported

### ISSUE THREAD

**Issue by Jaap-van-Hengstum** [nvdweem/intellij-sqlserver-backup-restore#17]
We have a mix of different SQL Server editions on our servers. Compressed backups are not supported in the Web edition. Would it be possible to check the SQL Server edition before doing the backup so the compression option can be applied when possible?

E.g.
```sql
SELECT SERVERPROPERTY('Edition') AS Edition
-- Edition == 'Web Edition (64-bit)' : compressed backups not supported
```

or
```sql
SELECT SERVERPROPERTY('EditionID') AS EditionID
-- EditionID == 1293598313  : compressed backups not supported
```

See:
https://docs.microsoft.com/en-us/sql/t-sql/functions/serverproperty-transact-sql?view=sql-server-ver15#:~:text=EditionID%20represents%20the%20installed%20product,by%20Edition%20of%20SQL%20Server.&text=Database%20Engine%20edition%20of%20the,Server%20installed%20on%20the%20server.

**Comment by nvdweem** [comment]
I made a change and submitted a new version of the plugin for approval.
Using the plugin on Express, 'Express with Advanced Services' and Web editions should mean that compression is not attempted even when it's turned on in the settings.
