### ISSUE TITLE
Restore issue folder path in Mac

### ISSUE THREAD

**Issue by Wavesolid** [nvdweem/intellij-sqlserver-backup-restore#26]
When I tried to restore the .bak file through the popup window, the folder path seems unusual, like this
<img width="693" alt="image" src="https://github.com/nvdweem/intellij-sqlserver-backup-restore/assets/58335667/248ba005-63b9-4945-9f75-4182c51c421d">

Even I tried to manually navigate it to `/Users/MyUser/Downloads` the folder path is rejecting and keep using those `mssqlDb:///` path.

**Comment by nvdweem** [comment]
Restoring a database on SQL server must (as far as I know) be done locally. The `mssqlDb://` means that you are browsing on the (remote) server. You have to put the backup somewhere that the database server can reach.

If you use a docker SQL server you can add a volume mapping. For networked servers you could share a folder on the server where you can place backups.

**Comment by Wavesolid** [comment]
I was in rush before and didn't notice it was my Docker directory folders not my local C. So yeah, I already figured it out and did manually move my `.bak` file to my Docker directory. Thank you so much for the respond.
