### ISSUE TITLE
Menu is gone after upgrade rider to 2024.3

### ISSUE THREAD

**Issue by trdmitry** [nvdweem/intellij-sqlserver-backup-restore#45]
**Describe the bug:**
After upgrade rider to 2024.3 the menu item Bakup/Restore is not showing.
I reinstalled plugin and also try on another computer.

**Steps to reproduce:** 
Open context menu on any database.

**Expected behavior:**
Backup/Restore menu item exists under diagram.

**Comment by nvdweem** [comment]
I've found the issue (the internal structure of the selection in the database view is changed), but the build is failing. I'll try to resolve that this afternoon so that the new version of the plugin can go through the verification process.

**Comment by trdmitry** [comment]
Everything works.
Thank you.
